{% set name = "domdf-python-tools" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/domdf_python_tools-{{ version }}.tar.gz
  sha256: 0ac5efa2ac648dca5653e386fe73aa995e66b215c9d16b7ee87e931322a1e6c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib-metadata >=3.6.0
    - importlib-resources >=3.0.0
    - natsort >=7.0.1
    - python >=3.6
    - typing-extensions >=3.7.4.1

test:
  imports:
    - domdf_python_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/domdf_python_tools
  summary: Helpful functions for Python 🐍 🛠️
  license: MIT
  license_file: LICENSE
  doc_url: https://domdf-python-tools.readthedocs.io/

extra:
  recipe-maintainers:
    - domdfcoding
