{% set name = "domdf-python-tools" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/domdf_python_tools-{{ version }}.tar.gz
  sha256: 2ae308d2f4f1e9145f5f4ba57f840fbfd1c2983ee26e4824347789649d3ae298

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - hatch-requirements-txt
  run:
    - python
    - importlib-metadata >=3.6.0  # [py<39]
    - importlib-resources >=3.0.0  # [py<39]
    - natsort >=7.0.1
    - typing-extensions >=3.7.4.1
  run_constrained:
    # dates
    - pytz>=2019.1

# We can`t enable pytest because conftest uses the coincidence package, which is unavailable on the main channel.
# The policy states that packages are not specifically built for testing.
test:
  imports:
    - domdf_python_tools
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/domdf_python_tools
  summary: Helpful functions for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Helpful functions for Python
  doc_url: https://domdf-python-tools.readthedocs.io/
  dev_url: https://github.com/domdfcoding/domdf_python_tools

extra:
  recipe-maintainers:
    - domdfcoding
